name: secrets

on: [push]

env: 

  STATIC_VAR: "This is a static environment variable"

jobs: 
  show-secrets:
    runs-on: ubuntu-latest
    steps: 
      - name: github_clone
        uses: actions/checkout@v4

      - name: env_display
        run: | 
          echo "static variable value: $STATIC_VAR"
          echo "github secret username: ${{secrets.}}"
          echo "static variable value: $STATIC_VAR"
    
